---
title: "ctDNA-sWG output individual datasets"
output: html_notebook
---

```{r,warnings=FALSE}
library(data.table)
library(ggplot2)
library(ggthemes)
source("src/load.sWG.R")
```

```{r}
if(!dir.exists('data/indv')){dir.create('data/indv')}
for(i in 1:nrow(data$meta)){
  j <- i + 4
  stopifnot( paste0(names(data$cns)[j],'.bam') == data$meta[i,fname] )
  x <- cbind(data$cns[,c(1:4,j),with=F],data$segments[,j,with=F])
  names(x)[5:6] <- c('copy.number','segment')
  write.csv(x,file=paste0('data/indv/',gsub('/','-',data$meta[i,Sample.name]),'.tsv'),quote=F,row.names=F)
}
```

```{r}
#x <- rbindlist(lapply(data$meta[,order(patient)],function(i){
x <- rbindlist(lapply(1:nrow(data$meta),function(i){
  j <- i + 4
  stopifnot( names(data$cns)[j] == data$meta[i,fname] )
  x <- data$segments[,c(2:4,j),with=F]
  names(x) <- c("Chromosome","Start","End","Segment_Mean")
  x$grp <- x[,c(1,which(diff(Segment_Mean)!=0)+1,.N+1),Chromosome][,rep(1:length(diff(V1)), diff(V1)),Chromosome][,V1]
  x <- x[,.(sample.ID=data$meta[i,Sample.name],Start=min(Start),End=max(End),log2.ratio=unique(Segment_Mean),.N),.(Chromosome,grp)][,-c('grp')][,.(sample.ID,Chromosome,Start,End,N,log2.ratio)]
  x
}))
write.table(x,"QDNA.combined.segments.tsv",quote=F,row.names = F,sep='\t')
```